-- 03A
SELECT *
FROM Barang
WHERE HARGA_SATUAN >= 10000
ORDER BY HARGA_SATUAN ASC;

-- 03B
SELECT *
FROM Pelanggan
WHERE NAMA_PELANGGAN LIKE %g% AND ALAMAT = 'BANDUNG';

-- 03C
SELECT
    T.KODE,
    T.TANGGAL,
    P.NAMA_PELANGGAN,
    B.NAMA_BARANG,
    T.JUMLAH_BARANG,
    B.HARGA_SATUAN,
    (T.JUMLAH_BARANG*B.HARGA_SATUAN) AS TOTAL
FROM
    TRANSAKSI T,
    PELANGGAN P,
    BARANG B
WHERE
    T.KODE_PELANGGAN = P.KODE AND
    T.KODE_BARANG = B.KODE

-- 03D
SELECT
    P.NAMA_PELANGGAN,
    SUM(T.JUMLAH_BARANG) AS JUMLAH,
    SUM(T.JUMLAH_BARANG*B.HARGA_SATUAN) AS TOTAL
FROM
    TRANSAKSI T,
    PELANGGAN P,
    BARANG B
WHERE
    T.KODE_PELANGGAN = P.KODE AND
    T.KODE_BARANG = B.KODE
GROUP BY P.NAMA_PELANGGAN
ORDER BY P.NAMA_PELANGGAN ASC